AWSTemplateFormatVersion: '2023-09-09'
Description: Data pipeline using EMR for processing S3 data and triggering with CloudWatch Events.

Resources:
  MyS3InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-input-data-bucket

  MyS3OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-output-data-bucket

  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: my-emr-cluster
      ReleaseLabel: emr-6.4.0
      Instances:
        MasterInstanceGroup:
          InstanceType: m5.xlarge
          InstanceCount: 1
        CoreInstanceGroup:
          InstanceType: m5.xlarge
          InstanceCount: 2
      Applications:
        - Name: Spark
      JobFlowRole: !Ref EMRInstanceProfile

  EMRInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EMRRole

  EMRRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRole
